### ISSUE TITLE
[BUG] Sub indicators on meters are drawn under solid bars and are not fully visible

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis-2.9.0#106]
**Describe the bug**

Sub indicators on meters are drawn under solid bars and are not fully visible.

**To Reproduce**

Choose a meter with sub indicators, e.g. EQ.
Define the meter to use a solid bar.
Exercise the meter and observe the sub indicator is drawn under the bar, not on top of the bar, and so is not fully visible.

**Expected behaviour**

Sub indicators are drawn over the top of solid and segmented bars on meters that have them.

**Desktop (please complete the following information):**

Windows 10 Pro, Thetis 2.9.0.8 x64 4/23/22

**Comment by ramdor** [comment]
this is not a bug but an unwanted feature Scott ;). It is already on my list of things to resolve, but is not an easy one to change right now. At the moment you will have to make do with the little bit that drops below the solid bar.

**Comment by w-u-2-o** [comment]
No worries. You can close this if you like since it's already on your list.
Thanks!

**Comment by ramdor** [comment]
The issue is a zorder problem. The meter that displays peak has a higher z order to the meter item that displays the average marker (they are not the same meter item, there are two of them overlayed). We are filling the peak when you select solid so it goes on top of the average marker. If we make the average marker a higher zorder, it now draws on top of the filled bar no problem, however it also draws over the peak value marker when they are the same value.

**Comment by w-u-2-o** [comment]
Three layers, then?

**Comment by ramdor** [comment]
yes, bar, and the two indicators, all different layers, but then i have to redo some of the configuration code that links through to the setup settings. No rest for the wicked :)

**Comment by ramdor** [comment]
fixed, a final post draw stage is implemented to resolve this
