### ISSUE TITLE
Weak audio on VFO B in split mode

### ISSUE THREAD

**Issue by N0RR1** [ramdor/Thetis-2.9.0#61]
Audio from VFO B signals is down >13 dB compared to VFO A in split mode. Problem is independent of Master/RX1 volume, left/right audio pan and MultiRX settings. (This was a also problem with several Flex Radio versions of PowerSDR and SmartSDR)

**Comment by ramdor** [comment]
video with tests : https://youtu.be/rStQWO5BYSg

Can not find an issue, seems ok here. I test RX2 levels and MultiRX in the video. I am using 100% AF for both main RX1 and sub RX1.  The issue might be that you do not get a value read out for the AF for RXsub (MultiRX) so it can be hard to match, which is why I set both to 100% and used the AGC gain to make sure things were the same.
