### ISSUE TITLE
When Using MultiRX and TXing MultiRX closes after TX

### ISSUE THREAD

**Issue by w3ub** [ramdor/Thetis-2.9.0#65]
If you use the MultiRX mode, and want to TX on the MultiRX VFO B frequency, you can, but after you release the PTT the MultiRX mode closes.

In my case, set VFO A to say 3.770, enable MultiRX, set VFOB to say 3.900. You can RX on both frequencies now.

Now change the TX to VFO B using the TX button in the VFO B area at the top. Hit PTT. You are TXing on the correct VFO B frequency, but afterwards the RX from the MultiRX VFO B just turns off and disappears, leaving the RX set to VFO A.

**Comment by ramdor** [comment]
this doesn't happen for me. What version of Thetis are you using? have you tried a new database to see if something is messed up there? (backup old first)

**Comment by w3ub** [comment]
I am using 2.9.06. I reset the database, it still does it. I turn on MultiRX, then set the TX to VFO B. At this time, the MultiRX and SPLIT buttons are lit up. I set the TX to VFO B by clicking on TX at the top.

But if I hit the PTT, I do indeed TX on the VFO B frequency, but the MultiRX button is no longer lit afterwards, and I am RXing on VFO A.

I noticed this a year of so ago and commented but got no replies. I also use the CTUN option, with the zoom set to max and sampling rate at 384k.

Doug

**Comment by w3ub** [comment]
An update. Did it again. Started without CTUN on and DUP on (I usually have them on). It behaved properly. Engaged CTUN. Still OK. Engaged DUP, and now the problem occurs. 

So, 7000DLE Mk II, latest SW, Protocol 2, 384k, CTUN/DUP on, zoom at max. I think you’ll see the issue that way.

Doug

**Comment by W2PA** [comment]
I was not able to duplicate this exactly, but I did observe this weirdness between the SPLIT button and the TX button on VFOB.  You can enter split mode by clicking on either button.  I also have a MIDI button to activate SPLIT.

1. Turn on MultiRX
2. Click the SPLIT or use the MIDI SPLIT command - VFOB TX button lights up
3. Confirm that the MIDI SPLIT button still toggles correctly and re-engage SPLIT operation
4. Click the TX button on VFOB
5. Now you can no longer toggle SPLIT off using the MIDI button.  You must use the console SPLIT button

I never use the TX button to enter split operation so I never noticed this before.  Step 3 is optional.  Even if you don't touch the MIDI control, clicking the TX button seems to disable the SPLIT operation via the MIDI interface.  

One other weirdness noted: Upon trying step 5 (toggling SPLIT off using the MIDI control), VFOB changes to the inactive color but the TX button remains lit.  And SPLIT is indeed still active - when I transmit it's on VFOB's frequency.

Note: other MIDI commands seem to be unaffected, although I of course didn't try them *all*.

Maybe this bug is related to Doug's bug, which I can't seem to replicate.

**Comment by ramdor** [comment]
there is an issue with multirx when the split gap is greater than samplerate_rx1/2 when TX'ing. The maths breaks and I wont have a chance this evening to investigate further. Perhaps tomorrow now.

If you bring multiRX (vfob) frequency close to vfoA freq the multirx shouldn't drop out

**Comment by w3ub** [comment]
Yes, you got it. If I bring VFO B closer to VFO A the problem does not occur.
Thanks for tracking it down!
Doug

**Comment by ramdor** [comment]
This is now fixed hopefully, although there may be some side effects I have missed.
